import { GoogleGenAI, HarmCategory, HarmBlockThreshold } from "@google/genai";
import { rateLimiter } from "./rateLimiter";
import { LineItem, RoomData, ProjectMetadata, ExtractedData, JobType } from "../types";
import { sanitizeLineItem, sortScopeItems } from "../utils/xactimateRules";
import { getSystemInstruction, buildUserPrompt } from "../utils/aiConfig";
import { enrichScopeWithLogistics } from "../utils/logisticsEngine";
import { sanitizeRooms } from "../utils/roomSanitizer";

const MODEL_NAME = "gemini-2.5-flash";
const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  console.error("API Key is missing. Please check your .env file.");
}

// --- TEXT STREAM PARSER ---
const parseTextResponse = (text: string): { rooms: RoomData[], metadata: ProjectMetadata } => {
  const lines = text.split('\n').map(l => l.trim()).filter(l => l.length > 0);
  const rooms: RoomData[] = [];
  let currentRoom: RoomData | null = null;
  let metadata: ProjectMetadata = { loss_type_inference: "Unknown", severity_score: 5, confidence_level: "Low" };

  for (const line of lines) {
    try {
      if (line.startsWith('META::')) {
        const parts = line.substring(6).split('|');
        if (parts.length >= 3) {
          metadata = {
            loss_type_inference: parts[0].trim() || "Unknown",
            severity_score: parseInt(parts[1].trim()) || 5,
            confidence_level: (parts[2].trim() as any) || "Low"
          };
        }
      } else if (line.startsWith('ROOM::')) {
        const parts = line.substring(6).split('|');
        currentRoom = {
          id: crypto.randomUUID(),
          name: parts[0]?.trim() || "Unknown Room",
          timestamp_in: parts.length >= 3 ? parts[1]?.trim() : "",
          narrative_synthesis: parts.length >= 3 ? parts[2]?.trim() : (parts[1]?.trim() || ""),
          flagged_issues: [],
          items: []
        };
        rooms.push(currentRoom);
      } else if (line.startsWith('ITEM::')) {
        if (!currentRoom) continue;
        const parts = line.substring(6).split('|');
        if (parts.length < 5) continue; 
        
        currentRoom.items.push(sanitizeLineItem({
            id: crypto.randomUUID(),
            category: parts[0].trim(),
            selector: parts[1].trim(),
            code: `${parts[0].trim()} ${parts[1].trim()}`,
            description: parts[6]?.trim() || "Item description",
            activity: parts[2].trim(),
            quantity: parseFloat(parts[3].trim()) || 1,
            quantity_inference: parts[3].trim(),
            unit: parts[4].trim(),
            reasoning: parts[7]?.trim() || "Generated by AI",
            confidence: (parts[5]?.trim() as any) || 'Low'
        }));
      }
    } catch (e) {
      console.warn("Skipping malformed line:", line);
    }
  }
  rooms.forEach(r => r.items = sortScopeItems(r.items));
  return { rooms, metadata };
};

// --- HELPER: File to Base64 ---
const fileToBase64 = (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => resolve((reader.result as string).split(',')[1]);
    reader.onerror = error => reject(error);
  });
};

export const generateScope = async (
  description: string,
  scopeContext: string,
  jobType: JobType,
  base64Images: string[] = [],
  videoData?: ExtractedData | null,
  audioFiles: File[] = [] 
): Promise<{ rooms: RoomData[], metadata: ProjectMetadata }> => {
  return rateLimiter.enqueue(async () => {
    const ai = new GoogleGenAI({ apiKey: API_KEY });
    const scopePhase = jobType === 'R' ? 'reconstruction' : 'mitigation';
    const parts: any[] = [{ text: buildUserPrompt(`${description} [Scope Context: ${scopeContext}]`, jobType) }];

    // 1. Add Video Data (Frames + Audio)
    if (videoData) {
      if (videoData.audio) {
        parts.push({ inlineData: { mimeType: "audio/wav", data: videoData.audio } });
      }
      videoData.frames.forEach(frame => {
        parts.push({ inlineData: { mimeType: "image/jpeg", data: frame } });
      });
    }

    // 2. Add Separate Audio Files
    for (const audioFile of audioFiles) {
      const base64Audio = await fileToBase64(audioFile);
      const mimeType = audioFile.type || "audio/mp3";
      parts.push({ inlineData: { mimeType, data: base64Audio } });
    }

    // 3. Add Photos
    base64Images.forEach(img => {
      const mimeMatch = img.match(/^data:(image\/[a-zA-Z+]+);base64,/);
      const mimeType = mimeMatch ? mimeMatch[1] : "image/jpeg";
      const data = img.replace(/^data:image\/[a-zA-Z+]+;base64,/, "");
      parts.push({ inlineData: { mimeType, data } });
    });

    try {
      const response = await ai.models.generateContent({
        model: MODEL_NAME,
        contents: { parts },
        config: {
          systemInstruction: getSystemInstruction(scopePhase),
          responseMimeType: "text/plain",
          temperature: 0.1,
          maxOutputTokens: 8192,
          safetySettings: [
            { category: HarmCategory.HARM_CATEGORY_HATE_SPEECH, threshold: HarmBlockThreshold.BLOCK_NONE },
            { category: HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT, threshold: HarmBlockThreshold.BLOCK_NONE },
            { category: HarmCategory.HARM_CATEGORY_HARASSMENT, threshold: HarmBlockThreshold.BLOCK_NONE },
            { category: HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT, threshold: HarmBlockThreshold.BLOCK_NONE },
          ]
        }
      });

      const candidate = response.candidates?.[0];
      let rawText = response.text || "";
      
      if ((!rawText || candidate?.finishReason === 'MAX_TOKENS') && candidate?.content?.parts) {
        rawText = candidate.content.parts.map((p: any) => p.text || '').join('');
      }
      if (!rawText) throw new Error("Empty response from AI.");

      const parsedResult = parseTextResponse(rawText);

      // --- CORRECCIÓN CRÍTICA AQUÍ ---
      // Antes: parsedResult.rooms = sanitizeRooms(...) -> ERROR
      // Ahora: Desempaquetamos el objeto correctamente
      const sanitized = sanitizeRooms(parsedResult.rooms);
      parsedResult.rooms = sanitized.rooms; // <--- ESTO ES LO QUE FALTABA
      
      // Log para debugging (opcional)
      if (sanitized.warnings.length > 0) {
          console.log("Sanitizer Logic:", sanitized.warnings);
      }
      // -------------------------------

      parsedResult.rooms = enrichScopeWithLogistics(
        parsedResult.rooms, 
        parsedResult.metadata.severity_score, 
        scopeContext,
        parsedResult.metadata.loss_type_inference,
        jobType
      );

      return parsedResult;

    } catch (error) {
      console.error("Gemini Core Engine Error:", error);
      throw error;
    }
  });
};